# Generated by Django 5.2 on 2025-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="expense_icon",
            field=models.CharField(blank=True, default="💸", max_length=255, null=True),
        ),
    ]
