# Generated by Django 5.2 on 2025-04-26 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expense_expense_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="expense_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
