# Generated by Django 5.2 on 2025-04-26 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
