# Generated by Django 5.2 on 2025-04-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_expensegroup_created_by_expensegroup_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensegroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
