# Generated by Django 5.2 on 2025-04-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_expensegroup_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensegroup",
            name="simplify_debt",
            field=models.BooleanField(default=False),
        ),
    ]
