# Generated by Django 5.2 on 2025-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_expensegroup_simplify_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensegroup",
            name="group_icon",
            field=models.CharField(blank=True, default="👥", max_length=255, null=True),
        ),
    ]
