name: Django CI

env:
  SECRET_KEY: asd
  DB_ENGINE: django.db.backends.postgresql
  DB_HOST: db.dfbvdfbvdf.supabase.co
  DB_PORT: 5432
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: dfgfgfdgfdgfdg
  DB_OPTIONS: require

  USE_LOCAL_LLM: false
  LOCAL_LLM_URL: http://localhost:11434/api/generate
  LLM_MODEL: codellama
  USE_SQLITE: true
  GEMINI_API_KEY: dummykey


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13, ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run precommit hooks
      run: |
        pre-commit run --all-files
    - name: Run Tests
      run: |
        python manage.py test
